name: pr_coverage_report
on:
  repository_dispatch:
      types: push_coverage_report
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6.3.3
              id: get-pr-number
              with:
                  script: |
                      const { data } = await github.rest.pulls.list({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      state: 'open',
                      head: '${{ github.event.client_payload.ref }}'
                      })
                      return data[0].number
                  result-encoding: string
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.client_payload.ref }}
            - name: get coverage-summary.json from CircleCI build
              run: |
                  covReport=$(curl -L ${{ github.event.client_payload.coverage_report_summary_url }} -H "Circle-Token: ${{ secrets.CCI_TOKEN }}")
                  mkdir -p coverage
                  echo ${covReport} | tee coverage/coverage-summary.json
            - name: Jest Coverage Comment
              id: coverage
              uses: MishaKav/jest-coverage-comment@v1.0.21
            - uses: marocchino/sticky-pull-request-comment@v2.3.1
              with:
                  number: ${{ steps.get-pr-number.outputs.result }}
                  message: |
                    White label coverage summary.
                    ${{ steps.coverage.outputs.summaryHtml }}
                    [See more details](${{ github.event.client_payload.coverage_report_details_url }})